In [1]:
import numpy as np

In [16]:
%%time
# declears 2-d numpy array (2-rows, 5-cols)
nums = np.array([[ 1 , 2,  3,  4,  5],[ 6,  7,  8,  9, 10]]) 
# Print second row of nums
print(nums[1,:])

# # Print all elements of nums that are greater than six
print( nums[nums > 6])

# Double every element of nums
nums_dbl = nums * 2
print(nums_dbl)

# # Replace the third column of nums
nums[ : , 2] = nums[ :, 2] + 1
print(nums)

[ 6  7  8  9 10]
[ 7  8  9 10]
[[ 2  4  6  8 10]
 [12 14 16 18 20]]
[[ 1  2  4  4  5]
 [ 6  7  9  9 10]]
CPU times: user 808 µs, sys: 141 µs, total: 949 µs
Wall time: 894 µs


In [12]:
#%lsmagic

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cat  %cd  %clear  %colors  %conda  %config  %connect_info  %cp  %debug  %dhist  %dirs  %doctest_mode  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %lf  %lk  %ll  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %lx  %macro  %magic  %man  %matplotlib  %mkdir  %more  %mv  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %rep  %rerun  %reset  %reset_selective  %rm  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%

In [4]:
val = 100 
val_2 = 1.7
print(val.__hash__)
print(val_2.__hash__)


<method-wrapper '__hash__' of int object at 0x00007FFDCE7F3390>
<method-wrapper '__hash__' of float object at 0x000001A4148DD5B0>
